SELECT EMP_ID , EMP_NAME , EMP_NO , EMAIL , PHONE , NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME , SALARY 
FROM EMPLOYEE e 
LEFT JOIN DEPARTMENT d ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;

SELECT EMP_ID , EMP_NAME , EMP_NO , EMAIL , PHONE , NVL(DEPT_TITLE, '부서없음') DEPT_TITLE , JOB_NAME , SALARY 
		FROM EMPLOYEE e 
		LEFT JOIN DEPARTMENT d ON(DEPT_ID = DEPT_CODE)
		JOIN JOB USING(JOB_CODE)
		WHERE EMP_ID = 223;
	
DROP FROM EMPLOYEE e WHERE EMP_ID = 223;


SELECT DEPT_ID , SUM(SALARY) MAX_SAL  
FROM EMPLOYEE e 
LEFT JOIN DEPARTMENT d ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
GROUP BY DEPT_ID
ORDER BY DEPT_ID;

SELECT * FROM EMPLOYEE;








