CREATE TABLE MAJOR(
MAJOR_NO NUMBER PRIMARY KEY, 
MAJOR_NM VARCHAR2(100) NOT NULL
);

SELECT * FROM MAJOR;

CREATE TABLE STUDENT(
STUDENT_ID NUMBER PRIMARY KEY,
STUDENT_NAME VARCHAR(20) NOT NULL,
GENDER VARCHAR2(3) CHECK( GENDER IN ('남', '여')),
BIRTH DATE ,
MAJOR_NO NUMBER,
FOREIGN KEY(MAJOR_NO) REFERENCES MAJOR ON DELETE SET NULL
);

SELECT * FROM STUDENT;

INSERT INTO MAJOR VALUES(1, '국어국문');
INSERT INTO MAJOR VALUES(2, '영어영문');
INSERT INTO MAJOR VALUES(3, '생물');
INSERT INTO MAJOR VALUES(4, '기계');
INSERT INTO MAJOR VALUES(5, '디자인');

INSERT INTO STUDENT VALUES(7, '홍길동', '남', TO_DATE( '2019-01-14', 'fxYYYY-MM-DD' ), 5);
INSERT INTO STUDENT VALUES(2, '김철수', '남', '1992-02-02', 3);
INSERT INTO STUDENT VALUES(3, '김남길', '여', '1993-03-03', 2);
INSERT INTO STUDENT VALUES(4, '이영희', '여', '1999-04-04', 1);
INSERT INTO STUDENT VALUES(5, '김세현', '여', '2000-05-05', 4);

SELECT * FROM MAJOR NATURAL JOIN STUDENT;

ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME; 














